### ISSUE TITLE
trainning error:AttributeError: 'module' object has no attribute 'ImageLabelDataParameter'

### ISSUE THREAD

**Issue by windforever118** [fyu/dilation#19]
when I run the train.py ,I get this error:
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 235, in main
    train_net, test_net = make_nets(options)
  File "train.py", line 112, in make_nets
    train_net = make_net(options, True)
  File "train.py", line 108, in make_net
    return globals()['make_' + options.model](options, is_training)
  File "train.py", line 55, in make_frontend_vgg
    is_training, options.crop_size, options.mean)
  File "/home/eric118/git/dilation/network.py", line 25, in make_image_label_data
    padding=P.ImageLabelData.REFLECT,
  File "/home/eric118/git/dilation/caffe-master/python/caffe/net_spec.py", line 220, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
AttributeError: 'module' object has no attribute 'ImageLabelDataParameter'
How can I fix it? Thank you very much!

**Comment by fyu** [comment]
Did you use my caffe for training? https://github.com/fyu/caffe-dilation

It is not necessary to run prediction.

**Comment by windforever118** [comment]
yeah，I forgot to change caffe-root , I used another caffe before. Thanks!

**Comment by vigorous0503** [comment]
Hi all,
Sorry, I have the same question, and I have already added the ${BUILD_DIR}/build_master/python into my PYTHONPATH, but it still appears the same error.

There is another stranger thing, after I make pycaffe, there is no caffe_pb2 in ${BUILD_DIR}/build_master/python/caffe/proto, and I try to copy it from original caffe which is already built, is it ok?

Thanks!

**Comment by fyu** [comment]
@vigorous0503 if caffe_pb2 doesn't exist, you can try to make clean and build the binary again. See if that solves your problem.

If you copy caffe_pb2 from original caffe, you will get the above error, since ImageLabelDataParameter doesn't exist in the original caffe.

**Comment by vigorous0503** [comment]
Hi , @fyu !
Thanks for your response!
I have try to make clean and make -j8 many times, but the error is still appear!
The following is what I have do...
I make the caffe-dilation under the "/home/bctsai/dilation/caffe-dilation/"
( I first copy Makefile.config.example to Makefile.config which is follow the original caffe ), 
and then make pycaffe( I also have export PYTHONPATH=/home/bctsai/dilation/caffe-dilation/build_master/python:$PYTHONPATH)

Thanks!

**Comment by Dandue** [comment]
I tried to use your caffe, and import caffe in the train.py, however, it turns out ImportError: No module named _caffe. When I use another caffe in predict.py, it works well. I don't know how to fix it. Could you help me? Thank you!

**Comment by fyu** [comment]
@Dandue Please check README of caffe-dilation. Or https://github.com/fyu/dilation/issues/11

**Comment by Dandue** [comment]
Sorry, I met a new problem about training. It seems that the process is pending after the first test before training begins, at Iteration 0. And I find no problem about the GPU memory, and no error message. I don't know how it happened.

**Comment by lillyro** [comment]
"Make sure that the Caffe version is newer than commit 08c5df."
So I use the latest version of caffe. But it still turns out AttributeError: 'module' object has no attribute 'ImageLabelDataParameter'. I also have changed the path of caffe root. 
Is it necessary for us to use the version of your own caffe?  https://github.com/fyu/caffe-dilation
What about other newer version of caffe?
Thank  you very much!
